services:
    postgres:
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        image: postgres:13.1
        restart: always
        ports:
            - "5434:5432"
        volumes:
          - db_data:/home/postgresql
          - db_data:/var/log/postgresql
        networks:
          - net

    app:
      container_name: tele_bot
      restart: always
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      volumes:
        - ./:/app/
      command: bash -c "python main.py"
      environment:
        - DATABASE_URL=postgresql+asyncpg://postgres:password@0.0.0.0:5434/postgres
      env_file:
        - environment
      expose:
        - 8080
      ports:
        - 8080:8080
      depends_on:
        - postgres
networks:
  net:

volumes:
    db_data:
        external: true