version: "3"

services:
  postgres:
      env_file:
        - environment
      image: postgres:13.1
      restart: always
      ports:
        - "5439:5432"
      volumes:
        - db_data:/home/postgresql
        - db_data:/var/log/postgresql
      networks:
        - net
volumes:
    db_data:
        external: true

