services:
    postgres:
        environment:
          POSTGRES_DB: test_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          PGDATA: "/home/postgresql/data"
        image: postgres:13.1
        restart: always
        ports:
            - "5440:5432"
        volumes:
          - db_data_1:/home/postgresql
          - db_data_1:/var/log/postgresql
        networks:
          - net

    app:
      container_name: tele_bot
      restart: always
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      volumes:
        - ./:/app/
      command: bash -c "python main.py"
      env_file:
        - environment
      ports:
        - 8080:8080
      depends_on:
        - postgres
      networks:
        - net
networks:
  net:

volumes:
    db_data_1:
        external: true