name: Run tests for homework

on: [push]

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Install inner (homework-level) dependencies
      run: |
        for d in homework_* ; do
          HW_REQUIREMENTS_PATH="$d/requirements.txt"
            if [ -f "$HW_REQUIREMENTS_PATH" ];
            then
              echo file \'"$HW_REQUIREMENTS_PATH"\' exists, installing...
              pip install -r "$HW_REQUIREMENTS_PATH";
            fi
        done
    - name: Install project-level dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
